using Microsoft.EntityFrameworkCore.Migrations;

namespace MovieRecommenderMVC.DAL.Migrations
{
    public partial class autogenerated : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
